env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy
brews:
  - tap:
      owner: hupe1980
      name: homebrew-notifier
    commit_author:
      name: hupe1980
    homepage:  https://github.com/hupe1980/notifier
    description: Tiny helper for publishing notifications on different platforms
    license: MIT
    test: |
      system "#{bin}/notifier -v"
scoop:
  bucket:
    owner: hupe1980
    name: notifier-bucket
  commit_author:
      name: hupe1980
  homepage:  https://github.com/hupe1980/notifier
  description: Tiny helper for publishing notifications on different platforms
  license: MIT
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/hupe1980/notifier
    maintainer: Frank Hübner <frankhuebner1980@gmail.com>
    description: Tiny helper for publishing notifications on different platforms
    license: MIT
    formats:
    - apk
    - deb
    - rpm
snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: Tiny helper for publishing notifications on different platforms
    description: |
      Tiny helper for publishing notifications on different platforms:
      * #slack
      * Amazon SNS
      * Microsoft Teams
      * Custom Webhooks 
      
      Examples:
      * nmap -p80,443 scanme.nmap.org | notifier -b
    grade: stable
    confinement: strict
    publish: true